### ISSUE TITLE
Documentação do Projeto

### ISSUE THREAD

**Issue by orlandosaraivajr** [KauaFT/PI_FATEC_2024_1Semestre#3]
Qual é o tema do software certo a ser feito ?

No dia 24/04, a equipe precisa ter claro qual o software o grupo pretende modelar, e apresentar os primeiros diagramas de **Caso de Uso**.

**Comment by KauaFT** [comment]
Agora de pouco a gente atualizou o README.mb especificando melhor o tema/ideia do site que queremos montar.

**Comment by orlandosaraivajr** [comment]
Acredito que esta issue não esteja plenamente fechada. O início do projeto foi feito, mas para a plena documentação do projeto, teremos mais melhorias a serem realizadas .

**Comment by orlandosaraivajr** [comment]
Em anexo, o template para a documentação, apresentado na aula de hoje.

Bom trabalho pessoal !
[Uploading Padrão Documentação ES1V1.odt…]()

**Comment by orlandosaraivajr** [comment]
Em anexo, o template para a documentação, desta vez em formado .docx
Bom trabalho pessoal !
[Projeto Integrador 1º Semestre.docx](https://github.com/KauaFT/PI_FATEC_2024_1Semestre/files/15255711/Projeto.Integrador.1.Semestre.docx)

**Comment by KauaFT** [comment]
Ok, obrigado
